name             'hygieia-dev-unbaked'
maintainer       'Drew Holt'
maintainer_email 'drew@liatrio.com'
license          'All rights reserved'
issues_url        'http://github.com/liatrio-chef/hygieia-dev-unbaked'
source_url        'http://github.com/liatrio-chef/hygieia-dev-unbaked'
description      'Installs/Configures a pipeline with hygieia dashboard'
long_description 'Installs/Configures a pipeline with hygieia dashboard'
version          '0.6.1'

# depends 'archiva-liatrio' # , '~> 0.0.0'
depends 'sonarqube-liatrio' # , '~> 0.0.0'
depends 'tomcat-liatrio' # , '~> 0.0.0'
depends 'jenkins-liatrio' # , '~> 0.0.0'
depends 'selenium-liatrio' # , '~> 0.0.0'
depends 'hygieia-liatrio' # , '~> 0.0.0'
